version: 2
jobs:
  build:
    working_directory: ~/main
    docker:
      - image: rocker/verse:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}-{{ checksum ".circleci/config.yml" }}
            - deps1-{{ .Branch }}
            - deps1-
      - run:
          command: |
            R -e "devtools::install_deps(dependencies = TRUE)"
            R -e "if(!require(goodpractice)) devtools::install_cran('goodpractice')"
      - run:
          command: |
            R -e 'devtools::check()'
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - "/usr/local/lib/R/site-library"
      - run:
          command: |
            mkdir /root/main/artifacts
            R -e "devtools::install()"
            R -e "goodpractice::gp(checks = grep('(rcmdcheck|covr)', goodpractice::all_checks(), invert=TRUE, value=TRUE))"
            R -e "cv <- covr::package_coverage(); print(cv); covr::report(x = cv, file = '/root/main/artifacts/{{<<PACKAGE_NAME>>}}-coverage.html', browse=FALSE); covr::codecov(coverage=cv)"
            R CMD Rd2pdf --force --output='/root/main/artifacts/{{<<PACKAGE_NAME>>}}-manual.pdf' .
      - store_artifacts:
          path: /root/main/artifacts/
          destination: artifacts

workflows:
   version: 2
   commit:
     jobs:
       - build
   nightly:
     triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - build
